name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Validate the structure of the pyproject.toml
        run: |
          poetry check

      - name: Verify that poetry.lock is consistent with pyproject.toml
        run: |
          poetry lock --check

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Run pre-commit hooks
        run: |
          poetry run pre-commit run --all-files

      - name: Run tests
        run: |
          poetry run coverage run shortuuid/runtests.py

      - name: Report coverage
        run: |
          poetry run coverage report -m --skip-covered
